# Generated by Django 3.1.7 on 2021-03-19 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=64)),
                ('channel_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userchannel',
            fields=[
                ('userchannel_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.channels')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.users')),
            ],
        ),
    ]
