# Generated by Django 3.1.7 on 2021-03-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210319_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
