# Generated by Django 3.1.7 on 2021-03-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_users_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchannel',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='userchannel',
            old_name='user_id',
            new_name='user',
        ),
    ]
