# Generated by Django 3.1.7 on 2021-03-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210319_0234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channels',
            new_name='Channel',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
