# Generated by Django 3.1.7 on 2021-03-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210319_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='users',
        ),
        migrations.CreateModel(
            name='Userchannel',
            fields=[
                ('userchannel_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.user')),
            ],
        ),
    ]
